import java.util.Date;

/**
 * @author Tyler Krawec
 * <p>
 * Class that creates the ProductionRecord of an object with user input from the GUI and generates
 * it a serial number and production date.
 */
public class ProductionRecord {

  int productID;
  int productionNum;
  String serialNum;
  Date prodDate;
  static int visCount;
  static int visMobCount;
  static int audCount;
  static int audMobCount;

  /**
   * Default constructor for a ProductionRecord object
   *
   * @param productId = Product id received from database
   */
  public ProductionRecord(int productId) {
    this.productID = productId;
    this.productionNum = 0;
    this.serialNum = "0";
    this.prodDate = new Date();
  }

  /**
   * Constructor for a ProductionRecord object
   *
   * @param productionNumber = Production number received from Production Record table
   * @param productId        = Product id received from Product table
   * @param serialNumber     = Serial number generated by ProductionRecord class received from
   *                         Production Record table
   * @param dateProduced     = Date the ProductionRecord object was produced received from
   *                         Production Record table
   */
  public ProductionRecord(int productionNumber, int productId, String serialNumber,
      Date dateProduced) {
    this.productionNum = productionNumber;
    this.productID = productId;
    this.serialNum = serialNumber;
    this.prodDate = dateProduced;
  }

  /**
   * Default constructor for a ProductionRecord object
   *
   * @param product = Product object received from list view selection in the GUI
   */
  public ProductionRecord(Product product) {
    this.prodDate = new Date();
    this.productID = product.getId();

    if (product.type == ItemType.AUDIO || product.type == ItemType.AUDIO_MOBILE) {
      audCount++;
      generateSerialNum(product, audCount);
    } else if (product.type == ItemType.VISUAL || product.type == ItemType.VISUAL_MOBILE) {
      visCount++;
      generateSerialNum(product, visCount);
    }
  }

  /**
   * Method for generating a serial number for a ProductionRecord based on attributes from the
   * received Product object
   *
   * @param product = Product object received from the list view selection in the GUI
   * @param enumCount = Count of the ItemType of the Product object to be produced
   */
  public void generateSerialNum(Product product, int enumCount) {

    String serialCount = String.format("%05d", enumCount);

    setSerialNum(
        product.getManufacturer().substring(0, 3).toUpperCase() + product.type.getItemCode()
            .substring(0, 2) + serialCount);
  }

  /**
   * Method for returning a ProductionRecord object's production number when called
   */
  public int getProductionNum() {
    return productionNum;
  }

  /**
   * Method for returning a ProductionRecord object's serial number when called
   */
  public String getSerialNum() {
    return serialNum;
  }

  /**
   * Method for setting ProductionRecord object's serial number from generateSerialNum
   */
  public void setSerialNum(String serialNum) {
    this.serialNum = serialNum;
  }

  /**
   * Method for returning a ProductionRecord object's production date when called
   */
  public Date getProdDate() {
    return prodDate;
  }

  /**
   * Method for returning a description of a ProductionRecord object when called
   */
  public String toString() {
    return "Prod. Num: " + productionNum + " Product ID: " + productID + " Serial Num: " + serialNum
        + " Date: " + prodDate + "\n";
  }
}
